### PR TITLE
Improve the pipeline and expand the container build

### PR DESCRIPTION
**Pull request by oscrx**
Hey Lars,

I saw there where some improvements to be made in the pipeline. Let me know if you have any questions.

Here is an example from the metadata on [a master build](https://github.com/oscrx/gitlab-ci-dashboard/actions/runs/4949575577/jobs/8851940850) (where i commented out the docker specific steps because i don't have the same secrets on my fork)

```json
  {
    "tags": [
      "ghcr.io/oscrx/gitlab-ci-dashboard:master",
      "ghcr.io/oscrx/gitlab-ci-dashboard:sha-d236319"
    ],
    "labels": {
      "org.opencontainers.image.title": "gitlab-ci-dashboard",
      "org.opencontainers.image.description": "Gitlab CI Dashboard will provide you a global overview of all pipelines/schedules and their status in Gitlab",
      "org.opencontainers.image.url": "https://github.com/oscrx/gitlab-ci-dashboard",
      "org.opencontainers.image.source": "https://github.com/oscrx/gitlab-ci-dashboard",
      "org.opencontainers.image.version": "master",
      "org.opencontainers.image.created": "2023-05-11T15:20:16.413Z",
      "org.opencontainers.image.revision": "d2363193c9a49d200b314f33cdebc18d34e55178",
      "org.opencontainers.image.licenses": "MIT"
    }
  }
  ```
  
  And here an example [when i released version v2.3.4](https://github.com/oscrx/gitlab-ci-dashboard/actions/runs/4949633386/jobs/8852097553)
  
  ```json
    {
    "tags": [
      "ghcr.io/oscrx/gitlab-ci-dashboard:2.3.4",
      "ghcr.io/oscrx/gitlab-ci-dashboard:2",
      "ghcr.io/oscrx/gitlab-ci-dashboard:2.3",
      "ghcr.io/oscrx/gitlab-ci-dashboard:sha-d236319",
      "ghcr.io/oscrx/gitlab-ci-dashboard:latest"
    ],
    "labels": {
      "org.opencontainers.image.title": "gitlab-ci-dashboard",
      "org.opencontainers.image.description": "Gitlab CI Dashboard will provide you a global overview of all pipelines/schedules and their status in Gitlab",
      "org.opencontainers.image.url": "https://github.com/oscrx/gitlab-ci-dashboard",
      "org.opencontainers.image.source": "https://github.com/oscrx/gitlab-ci-dashboard",
      "org.opencontainers.image.version": "2.3.4",
      "org.opencontainers.image.created": "2023-05-11T15:26:16.255Z",
      "org.opencontainers.image.revision": "d2363193c9a49d200b314f33cdebc18d34e55178",
      "org.opencontainers.image.licenses": "MIT"
    }
  }
  ```
  
  The images should be tagged the same for docker.io, but is's hard for me to test those.

### CODE REVIEW

**Comment by oscrx** [comment]
I removed the major and major+minor tag
But the Github sha tag option does not differentiate between a branch. Is it a problem if that tag is also published?

**Comment by larscom** [comment]
that is fine i guess ;-)

**Comment by oscrx** [comment]
I forgot a condition in the action where it updates the Docker Hub description.
This is not perfect though. It will run on any build that is not triggered by a pull request.
The build should succeed now though..

**Comment by larscom** [comment]
The branches have divirged to much, please re-open the PR when applicable.

**Pull request closed without merging**
